#!/usr/bin/env bash

BINDIR=$(dirname "$0")

echo "The directory is"
echo BINDIR

apt-get -y install nodejs
apt-get -y install npm

ls -la

cd BINDIR

ls -la

npm install && bower install && grunt build